name: 'Autotag GitHub Actions'
author: 'Plug Pagamentos - SRE Team'

inputs:
  repository:
    description: 'The path of the GitHub repository'
    required: true

  github_token:
    description: 'The GitHub Token with repo access'
    required: true

  git_username:
    description: 'GitHub account user name'
    required: true
  
  git_user_email:
    description: 'GitHub account user email'

runs:
  using: 'docker'
  image: './Dockerfile'