name: 'Autotag GitHub Actions'
author: 'Plug Pagamentos - SRE Team'

inputs:
  repository:
    description: 'The path of the GitHub repository'
    required: true

  github_token:
    description: 'The GitHub Token with repo access'
    required: true

runs:
  using: 'docker'
  image: './Dockerfile'